{{- if .Values.app.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.app.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
