# Docker image details
app_image: omerbenda98/ui_topia
stage_tag: 1
prod_tag: 1

# Application settings
app_name: ui_topia
container_name: ui_topia
app_port: 3000

# Environment-specific configurations
prod_nextauth_url: "http://localhost:3000" # Or use public IP if needed
stage_nextauth_url: "http://localhost:3000" # Or use public IP if needed
