# Secret for MongoDB credentials
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: staging
type: Opaque
data:
  # Base64 encoded values
  # username: admin (YWRtaW4=)
  # password: password123 (cGFzc3dvcmQxMjM=)
  mongodb-username: YWRtaW4=
  mongodb-password: cGFzc3dvcmQxMjM=

---
# ConfigMap for MongoDB configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: staging
data:
  mongodb-url: "mongodb://mongodb-service:27017"
  database-name: "myapp"

---
# PersistentVolumeClaim for data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi

---
# Deployment for MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: staging
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
# Service to expose MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: staging
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---