- name: Pull latest Docker image
  docker_image:
    name: "omerbenda98/ui_topia:{{ app_tag }}"
    source: pull
    force_source: yes

- name: Stop and remove existing container
  docker_container:
    name: ui_topia
    state: absent
    force_kill: yes

- name: Run app container
  docker_container:
    name: ui_topia
    image: "omerbenda98/ui_topia:{{ app_tag }}"
    restart_policy: always
    env:
      MONGODB_URI: "{{ mongodb_uri }}"
      NEXTAUTH_URL: "{{ environments[environment].nextauth_url }}"
      NEXTAUTH_URL_INTERNAL: "{{ environments[environment].nextauth_url }}"
      NEXTAUTH_SECRET: "{{ nextauth_secret }}"
      GOOGLE_ID: "{{ google_id }}"
      GOOGLE_CLIENT_SECRET: "{{ google_client_secret }}"
    ports: ["3000:3000"]

- name: Wait for container to start
  shell: docker ps | grep {{ container_name }} | grep -q "Up"
  register: container_status
  until: container_status.rc == 0
  retries: 10
  delay: 5
  ignore_errors: yes

- name: Set environment variable for Jenkins notification
  set_fact:
    ENVIRONMENT: "{{ environment }}"
    VERSION: "{{ app_tag }}"
  delegate_to: localhost
