- name: Stop and remove existing container
  docker_container:
    name: ui_topia
    state: absent
    force_kill: yes

- name: Run app container
  docker_container:
    name: ui_topia
    image: "omerbenda98/ui_topia:{{ app_tag }}"
    restart_policy: always
    env:
      MONGODB_URI: "{{ mongodb_uri }}"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
      NEXTAUTH_SECRET: "{{ nextauth_secret }}"
      GOOGLE_ID: "{{ google_id }}"
      GOOGLE_CLIENT_SECRET: "{{ google_client_secret }}"
    ports: "3000:3000"
