apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-addons
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/omerbenda98/uitopia-cd
    path: k8s/prometheus
    targetRevision: HEAD
    directory:
      recurse: true
      # Optional: exclude certain files
      # exclude: "*.tmp"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  # Use sync waves to ensure prometheus-stack deploys first
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
