apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.10.0
    chart: kube-prometheus-stack
    helm:
      values: |
        # Minimal configuration for testing
        grafana:
          enabled: true
          adminPassword: "admin"
          persistence:
            enabled: false  # Disable persistence for now
          ingress:
            enabled: false  # Disable ingress for now

        prometheus:
          enabled: true
          prometheusSpec:
            retention: 7d
            # Remove storage for now
            # storageSpec: null
            resources:
              requests:
                memory: 1Gi
                cpu: 500m
              limits:
                memory: 2Gi
                cpu: 1000m
          ingress:
            enabled: false  # Disable ingress for now

        alertmanager:
          enabled: true
          alertmanagerSpec:
            # Remove storage for now
            storage: null
          ingress:
            enabled: false  # Disable ingress for now

        # Keep these enabled as they're core components
        nodeExporter:
          enabled: true

        kubeStateMetrics:
          enabled: true

        prometheusOperator:
          enabled: true
          manageCrds: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
