apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.10.0
    chart: kube-prometheus-stack
    helm:
      values: |
        # Minimal configuration for testing
        grafana:
          enabled: true
          adminPassword: "admin"
          persistence:
            enabled: false  # Disable persistence for now
          ingress:
            enabled: true   # ENABLE THIS for external-DNS to work
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              # external-dns will automatically pick this up
            hosts:
              - grafana.benda.wiki
              
        prometheus:
          enabled: true
          
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - prometheus.benda.wiki

        alertmanager:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - alertmanager.benda.wiki

        # Keep these enabled as they're core components
        nodeExporter:
          enabled: true

        kubeStateMetrics:
          enabled: true

        prometheusOperator:
          enabled: true
          manageCrds: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
