- name: Add ubuntu user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
